### ISSUE TITLE
[BUG] 메모 검색에서의 Similarity 검색 답변 내용 오류

### ISSUE THREAD

**Issue by gee2450** [swm-null/null_null#37]
# 🚫 제목
메모 검색에서의 Similarity 검색 답변 내용 오류

## ✏ TODO
- [ ] 답변 관련 메모 리스트와 답변 내용이 조금 부자연스러움.

해결해줘

## 📖 참고 할만한 자료
![image](https://github.com/user-attachments/assets/cf2be3cc-3638-4bb6-9a61-a5876e8dc3a9)

**Comment by r4pidstart** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 이런건 뭐 어쨰야되는거야
