### ISSUE TITLE
[BUG] 태그 생성시 이전 태그가 무조건 들어가는 오류

### ISSUE THREAD

**Issue by gee2450** [swm-null/null_null#38]
# 🚫 제목
태그 생성시 이전 태그가 무조건 들어가는 오류

## ✏ TODO
- [ ] 태그가 별로 없을 때, 무조건 이전에 있던 태그가 다른 내용의 메모인데도 꼭 들어가는 오류가 생김

## 📖 참고 할만한 자료
![image](https://github.com/user-attachments/assets/497929db-a2f8-459e-a996-1a8576610ede)

**Comment by r4pidstart** [comment]
태그를 수십개 만들어보시면 이게 버그는 아니라는걸 알 순 있긴 할텐데요 ㅋㅋㅋㅋ

**Comment by r4pidstart** [comment]
여기말고 지라에 올려서 어사인 ㄱ
